name: Deploy to Vercel

on:
  push:
    branches:
      - '**'  # Deploy all branches

jobs:
  set-vercel-args:
    runs-on: ubuntu-latest
    outputs:
      args: ${{ steps.get-vercel-args.outputs.args }}
    steps:
      - id: get-vercel-args
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=args::--prod"
          else
            echo "::set-output name=args::"
          fi

  build_and_deploy:
    needs: set-vercel-args  # Ensures this job runs after set-vercel-args
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_APPWIZARD_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_CHATWIZARD_PROJECT_ID }}
          vercel-args: ${{ needs.set-vercel-args.outputs.args }}
          working-directory: webapp # Specify the directory containing the frontend
